---

- name: Stop AWX
  hosts: awx
  gather_facts: no
  tags:
    - never
    - awx_stop

  tasks:

    - name: Stop AWX components
      vars:
        pattern: 'Stopping\s+.*\s+\.\.\.\s+'
      command:
        cmd: "docker-compose -f ~/awx/tools/docker-compose/_sources/docker-compose.yml stop"
      register: stop_awx
      changed_when: stop_awx['stderr'] | default("") | regex_search(pattern)

    - name: Debug stop AWX components
      ansible.builtin.debug:
        var: stop_awx
        verbosity: "{{ verbosity_level | default(1) }}"
